# Configuration file for data paths

# CSV files
bundles_dataset: data/bundles_dataset.csv
bundles_product_match_train: data/bundles_product_match_train.csv
bundles_product_match_test: data/bundles_product_match_test.csv
product_dataset: data/product_dataset.csv

# Image directories
bundles_images: scratch/tesla8/sgrodriguez23/images/bundles_images
products_images: scratch/tesla8/sgrodriguez23/images/products_images
